version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    networks:
      - boilerplate_prod_network
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

networks:
  boilerplate_prod_network:
    external: true
    name: boilerplate_prod_network
